[build]
  publish = "public"
  functions = "functions"
  command = """
    # Create necessary directories (may be redundant if committed by Action)
    mkdir -p public/feeds
    mkdir -p functions/data/feeds
    
    # Copy necessary files for functions
    cp public/comics_list.json functions/ || true
    cp public/political_comics_list.json functions/ || true
    cp public/comics_list.json functions/data/ || true
    cp public/political_comics_list.json functions/data/ || true
    
    echo "Build command complete."
  """

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["comics_list.json", "political_comics_list.json", "data/**"]

# Direct /rss/ requests to the static feed files
[[redirects]]
  from = "/rss/*"
  to = "/feeds/:splat.xml"
  status = 200
  force = true

# REMOVED: Problematic fallback rule that might interfere with static serving
# [[redirects]]
#   from = "/feeds/*"
#   to = "/feeds/:splat"
#   status = 200

[build.environment]
  PYTHON_VERSION = "3.9"
  # Add environment variables for the feed generator
  MAX_WORKERS = "10"
  REQUEST_TIMEOUT = "10"
  MAX_RETRIES = "3"