[build]
  publish = "public"
  functions = "functions"
  command = """
    pip install -r requirements.txt
    pip install -e .
    python scripts/update_feeds.py
    mkdir -p public/feeds
    cp feeds/* public/feeds/
  """

[functions]
  directory = "functions"
  node_bundler = "esbuild"

# Direct /rss/ requests to the static feed files
[[redirects]]
  from = "/rss/*"
  to = "/feeds/:splat.xml"
  status = 200
  force = true

# Fallback for direct feed access
[[redirects]]
  from = "/feeds/*"
  to = "/feeds/:splat"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.9"