[build]
  publish = "public"
  functions = "functions"
  command = """
    # Install dependencies
    pip install -r requirements.txt
    pip install -e .
    
    # Update feeds
    python scripts/update_feeds.py
    
    # Create necessary directories
    mkdir -p public/feeds
    mkdir -p functions/data/feeds
    
    # Copy feed files to public directory
    cp feeds/* public/feeds/
    
    # Copy files to functions directory
    cp public/comics_list.json functions/data/
    cp -r public/feeds/* functions/data/feeds/
    
    # Verify files were copied
    echo "Verifying files in functions/data:"
    ls -la functions/data/
    echo "Verifying files in functions/data/feeds:"
    ls -la functions/data/feeds/
  """

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["data/**"]

# Direct /rss/ requests to the static feed files
[[redirects]]
  from = "/rss/*"
  to = "/feeds/:splat.xml"
  status = 200
  force = true

# Fallback for direct feed access
[[redirects]]
  from = "/feeds/*"
  to = "/feeds/:splat"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.9"