[build]
  publish = "public"
  functions = "functions"
  command = """
    # Install dependencies
    pip install -r requirements.txt
    pip install -e .
    
    # Update feeds
    python scripts/update_feeds.py
    
    # Create necessary directories
    echo "Creating directories..."
    mkdir -p public/feeds
    mkdir -p functions/data/feeds
    
    # Copy feed files
    echo "Copying feed files..."
    cp feeds/* public/feeds/
    
    # Copy and verify comics list
    echo "Copying comics list..."
    if [ ! -f public/comics_list.json ]; then
      echo "Error: comics_list.json not found in public directory"
      ls -la public/
      exit 1
    fi
    
    # Copy files to functions directory
    echo "Copying files to functions directory..."
    cp public/comics_list.json functions/data/
    cp -r public/feeds/* functions/data/feeds/
    
    # Verify the copy operation
    echo "Verifying file copy..."
    echo "Contents of functions/data:"
    ls -la functions/data/
    echo "Contents of functions/data/feeds:"
    ls -la functions/data/feeds/
    
    if [ ! -f functions/data/comics_list.json ]; then
      echo "Error: Failed to copy comics_list.json to functions/data/"
      exit 1
    fi
    
    # Print file sizes for verification
    echo "File sizes:"
    du -h functions/data/comics_list.json
    du -h functions/data/feeds/*.xml | wc -l
  """

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["data/**"]

# Direct /rss/ requests to the static feed files
[[redirects]]
  from = "/rss/*"
  to = "/feeds/:splat.xml"
  status = 200
  force = true

# Fallback for direct feed access
[[redirects]]
  from = "/feeds/*"
  to = "/feeds/:splat"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.9"