[build]
  publish = "public"
  functions = "functions"
  command = """
    pip install -r requirements.txt
    pip install -e .
    python scripts/update_feeds.py
    mkdir -p public/feeds
    cp feeds/* public/feeds/
    # Copy files needed for OPML generation
    mkdir -p functions/data/feeds
    # Ensure comics_list.json exists and copy it
    if [ ! -f public/comics_list.json ]; then
      echo "Error: comics_list.json not found in public directory"
      exit 1
    fi
    cp public/comics_list.json functions/data/
    cp -r public/feeds/* functions/data/feeds/
    # Verify the copy operation
    echo "Verifying file copy..."
    if [ ! -f functions/data/comics_list.json ]; then
      echo "Error: Failed to copy comics_list.json to functions/data/"
      exit 1
    fi
    ls -la functions/data/feeds/
    ls -la functions/data/comics_list.json
  """

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["data/**"]

# Direct /rss/ requests to the static feed files
[[redirects]]
  from = "/rss/*"
  to = "/feeds/:splat.xml"
  status = 200
  force = true

# Fallback for direct feed access
[[redirects]]
  from = "/feeds/*"
  to = "/feeds/:splat"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.9"