[build]
  publish = "public"
  functions = "functions"
  command = """
    # REMOVED Python dependency installation - not needed for build
    # pip install -r requirements.txt
    # pip install -e .
    
    # Create necessary directories (may be redundant if committed by Action)
    mkdir -p public/feeds
    mkdir -p functions/data/feeds
    
    # REMOVED file copying - function reads from deployed /public path
    # cp public/comics_list.json functions/ || true
    # cp public/comics_list.json functions/data/feeds/ || true
    # cp -r public/feeds/* functions/data/feeds/ || true
    
    # REMOVED verification logs - not needed for minimal build
    # echo "Verifying files..."
    # ls -la ...
    echo "Build command complete (no actions needed)."
  """

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["comics_list.json", "data/**"]

# Direct /rss/ requests to the static feed files
[[redirects]]
  from = "/rss/*"
  to = "/feeds/:splat.xml"
  status = 200
  force = true

# REMOVED: Problematic fallback rule that might interfere with static serving
# [[redirects]]
#   from = "/feeds/*"
#   to = "/feeds/:splat"
#   status = 200

[build.environment]
  PYTHON_VERSION = "3.9"
  # Add environment variables for the feed generator
  MAX_WORKERS = "10"
  REQUEST_TIMEOUT = "10"
  MAX_RETRIES = "3"