name: Tests

on:
  push:
    branches: [ main, test-branch-protection ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
      fail-fast: false  # Continue with other versions even if one fails

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
      id: setup-chrome

    - name: Setup ChromeDriver
      uses: browser-actions/setup-chromedriver@v1
      with:
        chromedriver-version: stable
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install package with test dependencies
        pip install -e ".[dev]"
        
    - name: Run tests with pytest
      continue-on-error: true  # Continue to show output even if tests fail
      env:
        PYTHONPATH: ${{ github.workspace }}
        CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}
        CHROMEDRIVER_PATH: chromedriver
      run: |
        # Print versions for debugging
        google-chrome --version
        chromedriver --version
        python -m pytest -v --cov=comiccaster --cov-report=xml --no-cov-on-fail
        
    - name: Upload coverage to Codecov
      if: success()
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true 